### ISSUE TITLE
Login with email

### ISSUE THREAD

**Issue by fab13n** [caracole-io/caracole.io#6]
Pour les circuits courts, j'avais posé que le username était égal à l'e-mail. Ça fait un truc de moins à retenir, et une occasion de moins de perdre les personnes mal à l'aise face à l'informatique. Il y avait un petit module Django pour y aider.

Je pense qu'on devrait poursuivre comme ça.

**Comment by nim65s** [comment]
C’est déjà le cas dans master, non ? Tu peux te logger avec ton email normalement.

**Comment by nim65s** [comment]
ah, non, au temps pour moi, je règle ça
